version: '3.8'
services:
  postgres:
    image: postgres
    container_name: cods_postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: cods_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL:  ${POSTGRES_EMAIL}
      PGADMIN_DEFAULT_PASSWORD:  ${POSTGRES_PASSWORD}
    ports:
      - "5050:80"

volumes:
  postgres_data:
